name = "Dionysos"
uuid = "d92c97cf-b87d-42c1-a9c0-25df00b4d958"
authors = ["Raphael Jungers <raphael.jungers@uclouvain.be>", "Antoine Aspeel <antoine.aspeel@uclouvain.be>", "Guillaume Berger <guillaume.berger@uclouvain.be>", "Julien Calbert <julien.calbert@uclouvain.be>", "Mahsa Farjadnia <mahsa.farjadnia@uclouvain.be>", "Beno√Æt Legat <benoit.legat@uclouvain.be>", "Zheming Wang <zheming.wang@uclouvain.be>", "Lucas N. Egidio <lucas.egidio@uclouvain.be>"]
version = "0.0.1"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
CUDD = "345a2cc7-28d8-58b2-abdf-cff77ea7d7f1"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiscreteMarkovChains = "8abcb7ef-b365-4f7b-ac38-56893fb62f9f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
HybridSystems = "2207ec0c-686c-5054-b4d2-543502888820"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
MechanismGeometries = "931e9471-e8fb-5385-a477-07ad12718aca"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ArnoldiMethod = "0.2"
CUDD = "0.2.1"
DataStructures = "0.18"
DiscreteMarkovChains = "0.2"
Distributions = "0.25"
FillArrays = "0.10, 0.11, 0.12, 0.13"
HybridSystems = "0.4"
JuMP = "0.23, 1"
LightXML = "0.9"
MathematicalSystems = "0.11, 0.12"
MechanismGeometries = "0.7"
MutableArithmetics = "1"
Plots = "1"
Polyhedra = "0.7"
ProgressMeter = "1.4"
SemialgebraicSets = "0.2"
SimpleWeightedGraphs = "1.2"
SpecialFunctions = "2"
StaticArrays = "1"
julia = "1.6"

[extras]
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Pavito = "cd433a01-47d1-575d-afb7-6db927ee8d8f"
SDPA = "b9a10b5b-afa4-512f-a053-bb3d8080febc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Cbc", "CDDLib", "Ipopt", "OSQP", "Pavito", "SDPA", "Test"]
