name = "Dionysos"
uuid = "d92c97cf-b87d-42c1-a9c0-25df00b4d958"
authors = ["Raphael Jungers <raphael.jungers@uclouvain.be>", "Antoine Aspeel <antoine.aspeel@uclouvain.be>", "Guillaume Berger <guillaume.berger@uclouvain.be>", "Julien Calbert <julien.calbert@uclouvain.be>", "Virginie Debauche <virginie.debauche@uclouvain.be>", "Mahsa Farjadnia <mahsa.farjadnia@uclouvain.be>", "Beno√Æt Legat <benoit.legat@uclouvain.be>", "Zheming Wang <zheming.wang@uclouvain.be>", "Lucas N. Egidio <lucas.egidio@uclouvain.be>", "Adrien Banse <adrien.banse@uclouvain.be>", "Somya Singh <somya.singh@uclouvain.be>"]
version = "0.1.2"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiscreteMarkovChains = "8abcb7ef-b365-4f7b-ac38-56893fb62f9f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
HybridSystems = "2207ec0c-686c-5054-b4d2-543502888820"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalLinearAlgebra = "92cbe1ac-9c24-436b-b0c9-5f7317aedcd5"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LatexPrint = "d2208f48-c256-5759-9089-c25ed2a93924"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
Libtiff_jll = "89763e89-9b03-5906-acba-b20f662cd828"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
ArnoldiMethod = "0.2, 0.4"
Colors = "0.12"
DataStructures = "0.18"
DiscreteMarkovChains = "0.2"
Distributions = "0.25"
FillArrays = "0.10, 0.11, 0.12, 0.13, 1"
GLPK = "1"
Graphs = "1"
HiGHS = "1"
HybridSystems = "0.4"
IntervalArithmetic = "0.20, 0.21, 0.22"
IntervalLinearAlgebra = "0.1"
JuMP = "1"
LaTeXStrings = "1"
LazySets = "2"
Libtiff_jll = "4.4.0"
LightXML = "0.9"
MathOptInterface = "1"
MathematicalSystems = "0.11, 0.12, 0.13"
MutableArithmetics = "1"
Plots = "1"
Polyhedra = "0.7"
ProgressMeter = "1.4"
RigidBodyDynamics = "2"
SemialgebraicSets = "0.2, 0.3"
SimpleWeightedGraphs = "1.2"
SpecialFunctions = "2"
StaticArrays = "1"
Suppressor = "0.2"
Symbolics = "5"
julia = "1.6"

[extras]
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Pavito = "cd433a01-47d1-575d-afb7-6db927ee8d8f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CDDLib", "Ipopt", "OSQP", "Pavito", "Clarabel", "Test", "HiGHS", "Mosek", "MosekTools"]
