name = "Dionysos"
uuid = "d92c97cf-b87d-42c1-a9c0-25df00b4d958"
authors = ["Raphael Jungers <raphael.jungers@uclouvain.be>", "Antoine Aspeel <antoine.aspeel@uclouvain.be>", "Guillaume Berger <guillaume.berger@uclouvain.be>", "Julien Calbert <julien.calbert@uclouvain.be>", "Mahsa Farjadnia <mahsa.farjadnia@uclouvain.be>", "Beno√Æt Legat <benoit.legat@uclouvain.be>", "Zheming Wang <zheming.wang@uclouvain.be>", "Lucas N. Egidio <lucas.egidio@uclouvain.be>"]
version = "0.0.1"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
CUDD = "345a2cc7-28d8-58b2-abdf-cff77ea7d7f1"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiscreteMarkovChains = "8abcb7ef-b365-4f7b-ac38-56893fb62f9f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
HybridSystems = "2207ec0c-686c-5054-b4d2-543502888820"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CDDLib = "0.9"
CUDD = "0.2.1"
CairoMakie = "0.8"
DataStructures = "0.18"
FillArrays = "0.10, 0.11, 0.12, 0.13"
HybridSystems = "0.3"
JuMP = "0.23, 1"
LazySets = "1.37"
MathematicalSystems = "0.11"
MutableArithmetics = "1"
Polyhedra = "0.7"
ProgressMeter = "1.4"
SemialgebraicSets = "0.2"
StaticArrays = "1"
julia = "1.6"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Pavito = "cd433a01-47d1-575d-afb7-6db927ee8d8f"
SDPA = "b9a10b5b-afa4-512f-a053-bb3d8080febc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SDPA", "Cbc", "Ipopt", "OSQP", "Pavito", "Test"]
