name = "Dionysos"
uuid = "d92c97cf-b87d-42c1-a9c0-25df00b4d958"
authors = ["Raphael Jungers <raphael.jungers@uclouvain.be>", "Antoine Aspeel <antoine.aspeel@uclouvain.be>", "Guillaume Berger <guillaume.berger@uclouvain.be>", "Julien Calbert <julien.calbert@uclouvain.be>", "Mahsa Farjadnia <mahsa.farjadnia@uclouvain.be>", "Beno√Æt Legat <benoit.legat@uclouvain.be>", "Zheming Wang <zheming.wang@uclouvain.be>"]
version = "0.0.1"

[deps]
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
CUDD = "345a2cc7-28d8-58b2-abdf-cff77ea7d7f1"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
HybridSystems = "2207ec0c-686c-5054-b4d2-543502888820"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
ParameterJuMP = "774612a8-9878-5177-865a-ca53ae2495f9"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CDDLib = "0.6"
CUDD = "0.2"
DataStructures = "0.18"
FillArrays = "0.10, 0.11"
HybridSystems = "0.3"
JuMP = "0.21"
LazySets = "1.37"
MathematicalSystems = "0.11"
MutableArithmetics = "0.2"
ParameterJuMP = "0.2, 0.3"
Polyhedra = "0.6.13"
ProgressMeter = "1.4"
PyPlot = "2.9"
SemialgebraicSets = "0.2"
StaticArrays = "0.12, 1.0"
julia = "1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Pavito = "cd433a01-47d1-575d-afb7-6db927ee8d8f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Cbc", "Ipopt", "OSQP", "Pavito", "Test"]
