[deps]
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
HybridSystems = "2207ec0c-686c-5054-b4d2-543502888820"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Pavito = "cd433a01-47d1-575d-afb7-6db927ee8d8f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "0.26"
